spring.application.name=ApiGateway
server.port=8222
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true

#management.endpoints.web.exposure.include=health,info, prometheus
management.endpoints.web.exposure.include=health,info

# Gateway discovery locator (auto-discovers services from Eureka)
spring.cloud.gateway.server.webmvc.discovery.locator.enabled=true
spring.cloud.gateway.server.webmvc.discovery.locator.lower-case-service-id=true

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/JobBoardKeycloack
#<sonar.projectKey>bitebloom-api-gateway</sonar.projectKey>
#<sonar.projectName>BiteBloom API Gateway</sonar.projectName>
#<sonar.host.url>http://localhost:9000</sonar.host.url>